console.log('🚫 GENERATE-HASH.JS - VERSION SÉCURISÉE');
console.log('========================================');
console.log('');
console.log('⚠️  ATTENTION : Les hashs sont déjà configurés !');
console.log('');
console.log('✅ Hashs actuellement en service :');
console.log('   CE1-1: fifamè');
console.log('   CE1-2: emmanuel');
console.log('   CE1-3: yinki');
console.log('   CE1-4: rahama');
console.log('   CE1-5: noham');
console.log('   CE1-6: queen');
console.log('   CE1-7: mékaddishem');
console.log('   CE1-8: faith');
console.log('   CE1-9: péniel');
console.log('   CE1-10: naelle');
console.log('');
console.log('📌 Pour modifier les hashs, éditez manuellement lib/users.js');
console.log('📌 Backup créé : lib/users.js.backup.*');
console.log('');
console.log('🌐 Application : http://localhost:3000');
console.log('🔐 Test : CE1-1 / fifamè');
console.log('');
process.exit(0);
